### ISSUE TITLE
Layers are broken in 1.3

### ISSUE THREAD

**Issue by marcnyc2001** [craigk5n/webcalendar#195]
I've recently upgraded to 1.3 and Layers seem to have broken...
I get the following error when loading the page from any of the users of the calendar:

Response:
<br />
<b>Deprecated</b>:  Methods with the same name as their class will not be constructors in a future version of PHP; Services_JSON has a deprecated constructor in <b>/home/marcurse/public_html/_OTHERSITES/saanenmoeser/includes/JSON.php</b> on line <b>115</b><br />
<br />
<b>Deprecated</b>:  Methods with the same name as their class will not be constructors in a future version of PHP; Services_JSON_Error has a deprecated constructor in <b>/home/marcurse/public_html/_OTHERSITES/saanenmoeser/includes/JSON.php</b> on line <b>781</b><br />
<br />
<b>Deprecated</b>:  Methods with the same name as their class will not be constructors in a future version of PHP; Services_JSON_Error has a deprecated constructor in <b>/home/marcurse/public_html/_OTHERSITES/saanenmoeser/includes/JSON.php</b> on line <b>795</b><br />
{"error":0,"status":"OK","message":"","layers":[{"id":"9","source":"Laurene","color":"","dups":"N","fullname":"Laurene"},{"id":"10","source":"Brigitte","color":"","dups":"N","fullname":"Brigitte"},{"id":"11","source":"Christine","color":"","dups":"N","fullname":"Christine"},{"id":"12","source":"Dominique","color":"","dups":"N","fullname":"Dominique"},

**Comment by craigk5n** [comment]
Fixed with latest commit 78bd245327e962ee584a2dff047c52ddc1193b5a

**Comment by marcnyc2001** [comment]
Apologies for re-opening this but I still get a similar error after having uploaded your new JSON.php file.
The first part of the error message (line 115) is still there:

`Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Services_JSON has a deprecated constructor in /home/marcurse/public_html/_OTHERSITES/saanenmoeser/includes/JSON.php on line 115`

The other two error messages have disappeared.

The page still does not load layers.

**Comment by marcnyc2001** [comment]
@craigk5n I am still getting the same error after applying the commit... how do I re-open this thread?

**Comment by marcnyc2001** [comment]
Also the error I am getting is on line 115, not in the 700's
Line 115 is the `class Services_JSON`
